config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Alonetone::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  constraints Greenfield::Constraints do
    mount Greenfield::Engine => "/"
  end

  constraints(->(req){ !Greenfield::Constraints.matches?(req) }) do
    resources :groups

    get '/login', :to => 'user_sessions#new', :as => 'login'
    match '/logout', :to => 'user_sessions#destroy', via: [:get, :post]
    resources :user_sessions

    # admin stuff
    get 'secretz' => 'secretz#index'

    get "/404", :to => "pages#four_oh_four"
    get '/500', :to => "pages#error"

    # one-off pages
    get 'rpmchallenge' => 'pages#rpm_challenge'
    get '24houralbum' =>  'pages#twentyfour'

    resources :features, :sessions, :user_reports

    get 'blog' => 'updates#index', :as => "blog_home"

    resources 'updates', :as => 'blog'
    resources :updates, :password_resets
    resources :comments do
      member do
        put :unspam
        put :spam
      end
    end

    get  'about/' => 'pages#index', :as => "about"
    get  'about/:action' => 'pages'
    get  'about/halp/:action' => 'pages', :as => "halp"

    get 'signup'    => 'users#new'
    get 'settings'  => 'users#edit'
    get '/activate/:perishable_token' => 'users#activate'


    # shortcut to profile
    get ':login/bio' => 'users#bio', :as => 'profile'

    get '/latest.:format' => 'assets#latest'

    # latest mp3s uploaded site-wide
    get '/latest/:latest' => 'assets#latest', :as => 'latest'

    get'/:login/listenfeed.:format' => 'assets#listen_feed', :as => 'listen_feed'

    get 'radio' =>'assets#radio', :as => 'radio_home'
    get 'radio/:source' => 'assets#radio', :defaults => {:per_page => 5, :page => 1}, :as => 'radio_source_home'
    get 'radio/:source/:per_page/:page' => 'assets#radio', :defaults => {:per_page => 5, :page => 1}, :as => 'radio'

    # top 40
    get  '/top/:top' => 'assets#top', :as => 'top'

    get '/users/by/activity/:page' => 'users#index', :sort => 'active', :defaults => {:page => 1}, :as => 'users_default'
    get '/users/(by/:sort(/:page))' => 'users#index', :defaults => {:page => 1}, :as => 'sorted_users'

    get ':login/history' => 'listens#index', :as => 'listens'

    get 'comments' => 'comments#index', :as => 'all_comments'
    get 'playlists' => 'playlists#all', :as => 'all_playlists'
    get ':login/comments' => 'comments#index', :as => 'user_comments'
    get ':login/stats.:format' => 'users#stats', :as => 'user_stats'

    get 'hot_track/:position.:format' => 'assets#hot_track',
        :format     => 'mp3',
        :as => 'hot_track'

    get ':login/plus' => 'source_files#index', :as => 'user_plus'

    resources :forums do
      resources :topics do
        resources :posts do
          member do
            put :unspam
            put :spam
          end
        end
      end
      resources :posts
    end

    resources :posts do
      collection do
        get :search
      end
    end


    get 'toggle_favorite' => 'users#toggle_favorite'

    match 'search' => 'search#index', via: [:get, :post]
    match 'search/:query' => 'search#index', :as => 'search_query', via: [:get, :post]

    namespace :admin do
      resources :layouts
      resources :users
    end


    root :to => 'assets#latest'

    resources :users
    get ':login' => 'users#show', :as => "user_home"
    get ':login.:format' => 'users#show', :as => "user_feeds"

    resources :users, :path => "/" do
      member do
        post :attach_pic
        get :sudo
        get :toggle_follow
      end
      resources 'source_files' #:path_prefix => ':login'
      resources 'tracks', :controller => :assets do
        member do
          get :share
          get :stats
        end
        collection do
          get  :latest
          post :search
          get  :mass_edit
        end
        resources :comments
      end
      resources :favorites
      resources :posts
      resources :playlists do
        collection do
          get :latest
          match :sort, :via => [:get, :post]
        end
        member do
          post :attach_pic
          get  :remove_track
          post :set_playlist_title
          post :set_playlist_description
          post :sort_tracks
          post :add_track
        end
        resources :comments
      end
    end
  end
end

app/controllers/secretz_controller.rb
class SecretzController < ApplicationController
  before_filter :require_login
  
  def index
    @ip_listens = Listen.most_active_ips
    @same_ip_users = User.with_same_ip
    @track_listens = Listen.most_active_tracks
    @all_time_track_listens = Asset.order('listens_count DESC').limit(25)
    @expensive_users = User.order('bandwidth_used desc').limit(25)
  end

end

app/helpers/secretz_helper.rb
module SecretzHelper
end

app/views/secretz/index.html.erb
<h2 class="table">Users that share the same IP</h2>
<div class="static_content secretz">
  <table id="listens_by_ip" class="statstable">
    <thead>
      <tr>
        <th>Country</th>
        <th>IP</th>
        <th>Users</th>
        <th>Examples</th>

      </tr>
    </thead>
    <tbody>
    <% @same_ip_users.each do |ip, count| %>
      <% users = User.where(:last_login_ip => ip).limit(5) %>
      <tr class>
        <td>
            <%= image_tag('http://api.hostip.info/flag.php?ip='+ip, :size => '20x20', :style => 'float:left; clear:none;opacity:0.4;') if ip %>
        </td>
        <td>
            <%= link_to(ip, 'http://www.botsvsbrowsers.com/ip/'+ip) if ip %>
        </td>
        <td>
          <%= count %>
        </td>
        <td>
            <%= users.collect{|u| link_to(u.name, user_path(u.login))}.join(" ").html_safe %>
        </td>
        <td></td>
       </tr>
    <% end %>
    </tbody>
  </table>
</div>


<h2 class="table">IPs that love to listen</h2>
<div class="static_content secretz">
  <table id="listens_by_ip" class="statstable">
    <thead>
      <tr>
        <th>Country</th>
        <th>IP</th>
        <th>Count</th>
        <th>User?</th>
      </tr>
    </thead>
    <tbody>
    <% @ip_listens.each do |ip, count| %>
      <tr class>
        <td>
            <%= image_tag('http://api.hostip.info/flag.php?ip='+ip, :size => '20x20', :style => 'float:left; clear:none;opacity:0.4;')%>
        </td>
        <td>
            <%= link_to ip, 'http://www.botsvsbrowsers.com/ip/'+ip %>
        </td>
        <td>
          <%= count %>
        </td>
        <td class="uploader">
            <% user = User.where(:last_login_ip => ip) %>
            <%= user.name if user %>
        </td>
        <td></td>
       </tr>
    <% end %>
    </tbody>
  </table>
</div>


<h2 class="table">Tracks that love to get played (last 30 days)</h2>
<div class="static_content secretz">
<table id="listens_by_track" class="statstable">
  <thead>
    <tr>
      <th>Track</th>
      <th>Count</th>
      <td>Uploader</td>
      <th>mp3 title</th>
      <th>mp3 artist</th>
    </tr>
  </thead>
  
  <tbody>
  <% @track_listens.each do |track, count| %>
    <tr class>
      <td><%= link_to track.name, user_track_path(track.user.login, track.permalink) %></td>
      <td><%= count %></td>
      <td class="uploader">
        <%= image_tag track.user.avatar(:tiny)%>
        <%= track.user.name %>
      </td>
      <td><%= track.title %></td>
      <td><%= track.artist %></td>
     </tr>
  <% end %>
  </tbody>
</table>
</div>


<h2 class="table">All time tracks by play count</h2>
<div class="static_content secretz">
  <table id="listens_by_track" class="statstable">
    <thead>
      <tr>
        <th>Track</th>
        <th>Count</th>
        <td>Uploader</td>
        <th>mp3 title</th>
        <th>mp3 artist</th>
      </tr>
    </thead>
  
    <tbody>
    <% @all_time_track_listens.each do |track| %>
      <tr class>
        <td><%= link_to track.name, user_track_path(track.user.login, track.permalink) %></td>
        <td><%= track.listens_count %></td>
        <td class="uploader">
          <%= image_tag track.user.avatar(:tiny)%>
          <%= track.user.name %>
        </td>
        <td><%= track.title %></td>
        <td><%= track.artist %></td>
       </tr>
    <% end %>
    </tbody>
  </table>
</div>


<h2 class="table">All time tracks by play count</h2>
<div class="static_content secretz">
  <table id="listens_by_track" class="statstable">
    <thead>
      <tr>
        <th>Track</th>
        <th>Count</th>
        <td>Uploader</td>
        <th>mp3 title</th>
        <th>mp3 artist</th>
      </tr>
    </thead>
  
    <tbody>
    <% @all_time_track_listens.each do |track| %>
      <tr class>
        <td><%= link_to track.name, user_track_path(track.user.login, track.permalink) %></td>
        <td><%= track.listens_count %></td>
        <td class="uploader">
          <%= image_tag track.user.avatar(:tiny)%>
          <%= track.user.name %>
        </td>
        <td><%= track.title %></td>
        <td><%= track.artist %></td>
       </tr>
    <% end %>
    </tbody>
  </table>
</div>



<h2 class="table">Top Bandwidth Users</h2>
<div class="static_content secretz">
  <table id="listens_by_track" class="statstable">
    <thead>
      <tr>
        <th>User</th>
        <th>Track Count</th>
        <th>GB used</th>
        <td>Cost</td>
      </tr>
    </thead>
  
    <tbody>
    <% @expensive_users.each do |user| %>
      <tr class>
        <td class="uploader">
          <%= image_tag user.avatar(:tiny)%>
          <%= link_to user.name, user_home_path(user.login) %></td>
        <td><%= user.assets_count %></td>
        <td>
          ~<%= user.bandwidth_used %> GB
        </td>
        <td><%= user.total_bandwidth_cost %></td>
       </tr>
    <% end %>
    </tbody>
  </table>
</div>