config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Alonetone::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  constraints Greenfield::Constraints do
    mount Greenfield::Engine => "/"
  end

  constraints(->(req){ !Greenfield::Constraints.matches?(req) }) do
    resources :groups

    get '/login', :to => 'user_sessions#new', :as => 'login'
    match '/logout', :to => 'user_sessions#destroy', via: [:get, :post]
    resources :user_sessions

    # admin stuff
    get 'secretz' => 'secretz#index'

    get "/404", :to => "pages#four_oh_four"
    get '/500', :to => "pages#error"

    # one-off pages
    get 'rpmchallenge' => 'pages#rpm_challenge'
    get '24houralbum' =>  'pages#twentyfour'

    resources :features, :sessions, :user_reports

    get 'blog' => 'updates#index', :as => "blog_home"

    resources 'updates', :as => 'blog'
    resources :updates, :password_resets
    resources :comments do
      member do
        put :unspam
        put :spam
      end
    end

    get  'about/' => 'pages#index', :as => "about"
    get  'about/:action' => 'pages'
    get  'about/halp/:action' => 'pages', :as => "halp"

    get 'signup'    => 'users#new'
    get 'settings'  => 'users#edit'
    get '/activate/:perishable_token' => 'users#activate'


    # shortcut to profile
    get ':login/bio' => 'users#bio', :as => 'profile'

    get '/latest.:format' => 'assets#latest'

    # latest mp3s uploaded site-wide
    get '/latest/:latest' => 'assets#latest', :as => 'latest'

    get'/:login/listenfeed.:format' => 'assets#listen_feed', :as => 'listen_feed'

    get 'radio' =>'assets#radio', :as => 'radio_home'
    get 'radio/:source' => 'assets#radio', :defaults => {:per_page => 5, :page => 1}, :as => 'radio_source_home'
    get 'radio/:source/:per_page/:page' => 'assets#radio', :defaults => {:per_page => 5, :page => 1}, :as => 'radio'

    # top 40
    get  '/top/:top' => 'assets#top', :as => 'top'

    get '/users/by/activity/:page' => 'users#index', :sort => 'active', :defaults => {:page => 1}, :as => 'users_default'
    get '/users/(by/:sort(/:page))' => 'users#index', :defaults => {:page => 1}, :as => 'sorted_users'

    get ':login/history' => 'listens#index', :as => 'listens'

    get 'comments' => 'comments#index', :as => 'all_comments'
    get 'playlists' => 'playlists#all', :as => 'all_playlists'
    get ':login/comments' => 'comments#index', :as => 'user_comments'
    get ':login/stats.:format' => 'users#stats', :as => 'user_stats'

    get 'hot_track/:position.:format' => 'assets#hot_track',
        :format     => 'mp3',
        :as => 'hot_track'

    get ':login/plus' => 'source_files#index', :as => 'user_plus'

    resources :forums do
      resources :topics do
        resources :posts do
          member do
            put :unspam
            put :spam
          end
        end
      end
      resources :posts
    end

    resources :posts do
      collection do
        get :search
      end
    end


    get 'toggle_favorite' => 'users#toggle_favorite'

    match 'search' => 'search#index', via: [:get, :post]
    match 'search/:query' => 'search#index', :as => 'search_query', via: [:get, :post]

    namespace :admin do
      resources :layouts
      resources :users
    end


    root :to => 'assets#latest'

    resources :users
    get ':login' => 'users#show', :as => "user_home"
    get ':login.:format' => 'users#show', :as => "user_feeds"

    resources :users, :path => "/" do
      member do
        post :attach_pic
        get :sudo
        get :toggle_follow
      end
      resources 'source_files' #:path_prefix => ':login'
      resources 'tracks', :controller => :assets do
        member do
          get :share
          get :stats
        end
        collection do
          get  :latest
          post :search
          get  :mass_edit
        end
        resources :comments
      end
      resources :favorites
      resources :posts
      resources :playlists do
        collection do
          get :latest
          match :sort, :via => [:get, :post]
        end
        member do
          post :attach_pic
          get  :remove_track
          post :set_playlist_title
          post :set_playlist_description
          post :sort_tracks
          post :add_track
        end
        resources :comments
      end
    end
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  before_validation :set_default_attributes, :on => :create
  before_update  :check_for_moved_forum
  after_update   :set_post_forum_id
  before_destroy :count_user_posts_for_counter_cache
  after_destroy  :update_cached_forum_and_user_counts

  scope :with_user, -> { preload(:last_user, :user) }
  scope :recent, -> { order('topics.created_at DESC') }
  scope :not_spam, -> { where(:spam => false).with_user }
  scope :spam,    ->  { where(:spam => true).with_user }
  scope :sticky_and_recent, -> { order("topics.sticky desc, topics.last_updated_at desc") }
  scope :for_footer, -> { recent.not_spam.includes(:recent_post => :user).includes(:forum).limit(3) }
  # creator of forum topic
  belongs_to :user
  
  # creator of recent post
  belongs_to :last_user, :class_name => "User"
  belongs_to :forum, :counter_cache => true

  has_many :posts, :dependent => :delete_all
   
  has_one  :recent_post,
    -> { not_spam.order('posts.created_at DESC') },
    :class_name => "Post"
  
  has_many :voices,
    -> { uniq },
    :through => :posts, :source => :user
  
  validates_presence_of :user_id, :forum_id, :title
  
  validates_presence_of :body, :on => :create

  attr_accessor :body
  attr_accessible :title, :body, :sticky, :locked
  attr_readonly :posts_count, :hits
  
  has_permalink :title, true
                               
  # hacks for defensio
  def article
    self
  end
  
  def author_name 
    user.login
  end
  
  def editable_by?(user)
    user && (user.id == user_id || user.moderator? || user.admin?)
  end
  
  def full_permalink
    "http://#{Alonetone.url}/forums/#{permalink}"
  end
  
  def sticky?
    sticky == 1
  end
  
  def hit!
    self.class.increment_counter :hits, id
  end

  def paged?
    posts_count > Post.per_page
  end
  
  def last_page
    [(posts_count.to_f / Post.per_page.to_f).ceil.to_i, 1].max
  end

  def update_cached_post_fields(post)
    # these fields are not accessible to mass assignment
    if remaining_post = post.frozen? ? recent_post : post
      update_columns(:last_updated_at => remaining_post.created_at, 
        :last_user_id => remaining_post.user_id,
        :last_post_id => remaining_post.id)
      Topic.reset_counters id, :posts
    else
      self.destroy
    end
  end
  
  def to_param
    permalink
  end

  def self.replied_to_by(user)
    user.posts.not_spam.select('distinct posts.topic_id, topics.*').order('topics.last_updated_at DESC').limit(5).joins(:topic)
  end

  def self.popular
    Post.group(:topic).not_spam.where(['posts.created_at > ?',10.days.ago]).limit(3).order('count_all DESC').count
  end

  def self.replyless
    Topic.not_spam.limit(3).order('created_at DESC').where(:posts_count => 1)
  end

protected
  
  def set_default_attributes
    self.sticky          ||= 0
    self.last_updated_at ||= Time.now.utc
  end

  def check_for_moved_forum
    old = Topic.find(id)
    @old_forum_id = old.forum_id if old.forum_id != forum_id
    true
  end

  def set_post_forum_id
    return unless @old_forum_id
    posts.update_all :forum_id => forum_id
    Forum.decrement_counter(:topics_count, @old_forum_id)
    Forum.increment_counter(:topics_count, forum_id)
  end
  
  def count_user_posts_for_counter_cache
    @user_posts = posts.group_by { |p| p.user_id }
  end
  
  def update_cached_forum_and_user_counts
    Forum.where(:id => forum_id).update_all "posts_count = posts_count - #{posts_count}"
    @user_posts.each do |user_id, posts|
      User.where(:id => user_id).update_all "posts_count = posts_count - #{posts.size}"
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :find_forum
  before_filter :find_topic, :only => [:show, :edit, :update, :destroy]
  before_filter :require_login, :only => [:create, :update]
  layout "forums"

  def index
    redirect_to forum_path(@forum)
  end
  
  def edit
  end

  def show
    set_session_topics
    @topic.hit! unless logged_in? && @topic.user_id == current_user.id
    if params[:spam]
      @posts = @topic.posts.recent
    else
      @posts = @topic.posts.recent.not_spam
    end
    @posts = @posts.preload(:user => :pic).page current_page
    @post  = Post.new
  end

  def new
    redirect_to(login_url) and return false unless logged_in?
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml  => @topic }
    end
  end

  def create
    @topic = current_user.post @forum, params[:topic], request
    if @topic.new_record?
      render :action => "new" 
    else
      flash[:notice] = 'Topic was successfully created.'
      redirect_to(forum_topic_path(@forum, @topic)) 
    end
  end

  def update
    current_user.revise @topic, params[:topic]
    if @topic.errors.empty?
      redirect_to(forum_topic_path(@topic.forum, @topic), :notice => 'Topic was updated.')
    else
      render :action => "edit" 
    end
  end

  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(@forum) }
      format.xml  { head :ok }
    end
  end

protected

  def set_session_topics
    if @topic
      ((session[:topics] ||= {})[@topic.id] = Time.now.utc) if logged_in?
    end 
  end 

  def authorized?
    !%w(destroy edit update).include?(action_name) ||
      current_user_is_admin_or_moderator_or_owner?(@topic.user)
  end
  
  def find_forum
    @forum = Forum.where(:permalink => params[:forum_id]).take!
  end
  
  def find_topic
    @topic = @forum.topics.where(:permalink => params[:id]).take!
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<p>
  <label for="topic_title"><%= 'Title' %></label><br />
  <%= form.text_field :title, :class => "primary", :tabindex => 10 %>

  <% if moderator? %>
  <label style="margin-left:1em;">
  <%= form.check_box :sticky %> <%= 'Sticky'%>
  </label>

  <label style="margin-left:1em;">
  <%= form.check_box :locked %> <%= 'Locked' %>
  </label>
  <% end -%>
</p>

<% if @topic.new_record? -%>
<p>
	<label for="topic_body"><%= 'Body' %></label><br />
	<%= form.text_area :body, :rows => 12, :tabindex => 20 %>
</p>
<% end -%>

<% if admin? && !@topic.new_record? && forums = Forum.ordered -%>
	<% if forums.size > 1 -%>
    <p id="topic_forum_id">
      <label for="topic_forum_id"><%= 'Forum' %></label><br />
      <%= form.select :forum_id, forums.map {|x| [x.name, x.id] } %></p>
    </p>
	<% end -%>
<% end -%>

app/views/topics/_quick_form.html.erb
<%= form_for @forum_feedback, :url  => user_reports_path do |f| -%>
<table>
    <tbody>
        <tr>
            <td class='label'>
               <label for="category">What's up?</label>
            </td>
            <td>
                <%= f.select 'forum_id',{"Something isn't working" => :bug, "I have an idea" => :idea, "I really really like" => :praise}%>
            </td>
        </tr>
        <tr>
            <td class='label'>
                <label for="topic_body"><%= 'Subject' %></label>
            </td>
            <td>
                <%= f.text_field :title, :class => 'subject' %>
            </td>
        </tr>
        <tr>
            <td class='label'>
                <label for="topic_body"><%= 'Details' %></label>
            </td>
            <td>
                <%= f.text_area :body, :rows => 7 %>
            </td>
        </tr>
    </tbody>
</table>        
            
	<div class="submit_wrapper">
	  <div class="comment_waiting" >
          <div class="text"><!-- placeholder response text --></div>
        </div>
    <div class="small_spinner" style="display:none;"></div>
	  <%= submit_tag 'Post feedback to forum', :id=>'bug_form_sumbit' %> or <%= link_to 'close', '#', :id=> 'nevermind', :class => 'feedback' %>
	</div>

<% end %>

app/views/topics/edit.html.erb
<% content_for :h1 do %> Edit Topic <% end %>

<div class="forum_form_container container static_content">
	<%= error_messages_for :topic %>
	<%= form_for :topic,
	     :url  => forum_topic_path(@forum, @topic),
	     :html => { :method => :put } do |f| -%>
	<%= render :partial => "form", :object => f %>
	<br>
	<%= submit_tag 'Save Changes' %> or <%= link_to('Cancel', forum_topic_path(@forum, @topic)) %>
	<% end -%>
</div>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
  </tr>

<% for topic in @topics %>
  <tr>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New topic', new_topic_path %>

app/views/topics/new.html.erb
<% content_for :h1 do %> alonetone forums: Starting a new topic <% end %>
<% content_for :breadcrumbs do %>
  <%= link_to 'Forums', forums_path %> <span class="arrow">&rarr;</span>
  <%= link_to @forum.name, forum_path(@forum) %> <span class="arrow">&rarr;</span> New Topic
<% end %>


<div class="container static_content">
  <p class="subtitle">Post will be by <%= current_user.name %> in the "<%= @forum.name %>" forum</p>
  <%= error_messages_for :topic %>
  <%= form_for :topic,
       :url  => forum_topics_path(@forum) do |f| -%>
  <%= render :partial => "form", :object => f %>
  <div class="submit_wrapper">
    <%= f.submit 'Post Topic' %> or  <%= link_to('Cancel', forum_path(@forum)).html_safe %>
  </div>
  <% end %>
  
  <%= render :partial => 'posts/formatting' %>       

</div>  

app/views/topics/show.html.erb
<% content_for :sidebar do %>
    <div class="sidebar forum">
      <div class="box"> 
          <h2 class="box static">Who's talking?</h2>
          <div class="static_content">
            <ul class="talking">
            <% @topic.voices.each do | user | %>
              <li><%= link_to h(user.display_name), user_path(user.login) %></li>
            <% end %>
            </ul>
          </div>
      </div>
    </div>
<% end %>

<% content_for :h1 do %> 
    <%= @topic.title %>
    <% if @topic.locked? %>
        <span>(locked)</span>
    <% end %>
<% end %> 

<% content_for :breadcrumbs do %>
    <%= link_to 'alonetone forums', forums_path %>  <span class="arrow">&rarr;</span> 
    <%= link_to h(@topic.forum.name),forum_path(@topic.forum) %> <span class="arrow">&rarr;</span> 
    <%= link_to @topic.title, forum_topic_path(@topic.forum, @topic) %>
    <% page=session[:forum_page] ? session[:forum_page][@topic.forum.id] : nil
    if page and page!=1 %>
        <small style="color:#ccc">
          (<%= link_to "page #{page}", forum_path(:id => @topic.forum, :page => page) %>)
        </small>
    <% end %>
<% end %>

<% @page_title = "#{@topic.title} - alonetone forums "%>
    
<% content_for :extras do %>
  <%= pluralize @topic.posts.size, 'post' %>, 
  <%= pluralize @topic.voices.size, 'person' %> talking
  <%= feed_icon_tag @topic.title, posts_path(:format => :atom,:forum_id => @forum, :topic_id => @topic) %>
<% end %>

<h2><%= @topic.title %></h2>
<% if moderator? || admin? %>
  <div class="topic_edit_and_delete_links">
    <%= link_to 'edit', edit_forum_topic_path(@topic.forum, @topic) %>
    &nbsp;/&nbsp;
    <%= link_to 'delete', forum_topic_path(@topic.forum, @topic), :method => :delete, :confirm => 'You want to delete this thread (and all replies?)' %> 
  </div>
<% end %>

<% if @posts.total_pages > 1 %>
  <div class="forum_paginator">
      <%= will_paginate @posts %>
  </div>
<% end %>

<table class="posts wide">
  <%= render @posts %>
</table>

<% if @posts.total_pages > 1 %>
<div class="forum_paginator">
  <%= will_paginate @posts %>
</div>
<% end %>

<% if logged_in? %>
  <div id="edit"></div>
  <% if @topic.locked? -%>
    <p>
      <%= image_tag "icons/private.png", :class => "icon grey", :title => "Topic locked" %> 
      <label>
      <%= 'This topic is locked (you cannot add a reply)' %></label>
    </p>
  <% else -%>
    <div id="reply" class="editbox">
      <div class="container static_content">
        <h3>Reply:</h3>
        <%= form_for :post, :url => forum_topic_posts_path(@forum, @topic, :page => @topic.last_page) do |f| -%>
          <%= f.text_area :body, :rows => 8, :cols => 40 %>
          <div class="submit_wrapper">
            <%= submit_tag "Post Reply" %>
          </div>
        <% end -%>
        <%= render :partial => 'posts/formatting' %>       
      </div>
    </div>
  <% end %>
<% else %>
  <div class="forum_login">
    <%= link_to 'login',   login_path %> or 
  	<%= link_to 'sign up', signup_path %> to reply
  </div>
<% end %>