config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Alonetone::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  constraints Greenfield::Constraints do
    mount Greenfield::Engine => "/"
  end

  constraints(->(req){ !Greenfield::Constraints.matches?(req) }) do
    resources :groups

    get '/login', :to => 'user_sessions#new', :as => 'login'
    match '/logout', :to => 'user_sessions#destroy', via: [:get, :post]
    resources :user_sessions

    # admin stuff
    get 'secretz' => 'secretz#index'

    get "/404", :to => "pages#four_oh_four"
    get '/500', :to => "pages#error"

    # one-off pages
    get 'rpmchallenge' => 'pages#rpm_challenge'
    get '24houralbum' =>  'pages#twentyfour'

    resources :features, :sessions, :user_reports

    get 'blog' => 'updates#index', :as => "blog_home"

    resources 'updates', :as => 'blog'
    resources :updates, :password_resets
    resources :comments do
      member do
        put :unspam
        put :spam
      end
    end

    get  'about/' => 'pages#index', :as => "about"
    get  'about/:action' => 'pages'
    get  'about/halp/:action' => 'pages', :as => "halp"

    get 'signup'    => 'users#new'
    get 'settings'  => 'users#edit'
    get '/activate/:perishable_token' => 'users#activate'


    # shortcut to profile
    get ':login/bio' => 'users#bio', :as => 'profile'

    get '/latest.:format' => 'assets#latest'

    # latest mp3s uploaded site-wide
    get '/latest/:latest' => 'assets#latest', :as => 'latest'

    get'/:login/listenfeed.:format' => 'assets#listen_feed', :as => 'listen_feed'

    get 'radio' =>'assets#radio', :as => 'radio_home'
    get 'radio/:source' => 'assets#radio', :defaults => {:per_page => 5, :page => 1}, :as => 'radio_source_home'
    get 'radio/:source/:per_page/:page' => 'assets#radio', :defaults => {:per_page => 5, :page => 1}, :as => 'radio'

    # top 40
    get  '/top/:top' => 'assets#top', :as => 'top'

    get '/users/by/activity/:page' => 'users#index', :sort => 'active', :defaults => {:page => 1}, :as => 'users_default'
    get '/users/(by/:sort(/:page))' => 'users#index', :defaults => {:page => 1}, :as => 'sorted_users'

    get ':login/history' => 'listens#index', :as => 'listens'

    get 'comments' => 'comments#index', :as => 'all_comments'
    get 'playlists' => 'playlists#all', :as => 'all_playlists'
    get ':login/comments' => 'comments#index', :as => 'user_comments'
    get ':login/stats.:format' => 'users#stats', :as => 'user_stats'

    get 'hot_track/:position.:format' => 'assets#hot_track',
        :format     => 'mp3',
        :as => 'hot_track'

    get ':login/plus' => 'source_files#index', :as => 'user_plus'

    resources :forums do
      resources :topics do
        resources :posts do
          member do
            put :unspam
            put :spam
          end
        end
      end
      resources :posts
    end

    resources :posts do
      collection do
        get :search
      end
    end


    get 'toggle_favorite' => 'users#toggle_favorite'

    match 'search' => 'search#index', via: [:get, :post]
    match 'search/:query' => 'search#index', :as => 'search_query', via: [:get, :post]

    namespace :admin do
      resources :layouts
      resources :users
    end


    root :to => 'assets#latest'

    resources :users
    get ':login' => 'users#show', :as => "user_home"
    get ':login.:format' => 'users#show', :as => "user_feeds"

    resources :users, :path => "/" do
      member do
        post :attach_pic
        get :sudo
        get :toggle_follow
      end
      resources 'source_files' #:path_prefix => ':login'
      resources 'tracks', :controller => :assets do
        member do
          get :share
          get :stats
        end
        collection do
          get  :latest
          post :search
          get  :mass_edit
        end
        resources :comments
      end
      resources :favorites
      resources :posts
      resources :playlists do
        collection do
          get :latest
          match :sort, :via => [:get, :post]
        end
        member do
          post :attach_pic
          get  :remove_track
          post :set_playlist_title
          post :set_playlist_description
          post :sort_tracks
          post :add_track
        end
        resources :comments
      end
    end
  end
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
      
  acts_as_list :scope => :user_id, :order => :position

  scope :mixes,            -> { where(:is_mix => true)                                                            }
  scope :albums,           -> { where(:is_mix => false).where(:is_favorite => false)                              }
  scope :favorites,        -> { where(:is_favorite => true)                                                       }
  scope :only_public,      -> { where(:private => false).where(:is_favorite => false).where("tracks_count > 1")   }
  scope :include_private,  -> { where(:is_favorite => false)                                                      }
  scope :recent,           -> { order('playlists.created_at DESC')                                                }
  scope :with_pic,         -> { includes(:pic).where.not(:pics => {:id => nil }).references(:pic)                 }
  scope :for_home,         -> { recent.only_public.limit(12).with_pic.includes(:user)                                  }

  belongs_to :user, :counter_cache => true  
  has_one  :pic, :as => :picable, :dependent => :destroy
  has_many :tracks,
     -> {order(:position).includes(:asset => :user)},
     :dependent => :destroy
  has_many :assets, :through => :tracks 
  
  validates_presence_of :description, :title, :user_id
  validates_length_of   :title, :within => 4..100
  validates_length_of   :year, :within => 2..4, :allow_blank => true
  validates_length_of   :description, :within => 1..2000, :allow_blank => true
    
  attr_accessible :user_id, :is_favorite, :year, :title, :description, :private, :position
  
  has_permalink :title
  before_validation  :name_favorites_and_set_permalink, :on => :create
  before_update :set_mix_or_album
  before_update :ensure_private_if_less_than_two_tracks

  def to_param
    "#{permalink}"
  end
  
  def dummy_pic(size)
    case size
      when :small then 'default/no-cover-50.jpg' 
      when :large then 'default/no-cover-125.jpg'
      when :album then 'default/no-cover-200.jpg' 
      when nil then 'default/no-cover-400.jpg'
    end 
  end
  
  def type
    is_mix? ? 'mix' : 'album'
  end
  
  def cover(size=nil)
    return dummy_pic(size) if has_no_cover?
    self.pic.pic.url(size)
  end
  
  def has_no_cover?
     Alonetone.try(:default_user_images) or !self.pic.present? or self.pic.new_record? or !self.pic.try(:pic).present?
  end
  
  def has_tracks?
    (self.tracks_count || 0) > 0
  end

  def empty?
    !has_tracks?
  end
  
  def play_time
    total_track_length = tracks.inject(0) do |total, track| 
      total += track.asset_length || 0
    end
    Asset.formatted_time(total_track_length)
  end
  
  def self.latest(limit=5)
    self.where('playlists.tracks_count > 0').includes(:user).limit(limit).order('playlists.created_at DESC')
  end
  
  def ensure_private_if_less_than_two_tracks
    self.private = true if !is_favorite? and tracks_count < 2
    true
  end
  
  # playlist is a mix if there is at least one track with a track from another user  
  def set_mix_or_album
    # is this a favorites playlist?
    is_mix = true if is_favorite?
    is_mix = true if tracks.present? && tracks.count > tracks.count(:all, :conditions => ['user_id != ?',user.id])
    true
  end
  
  # if this is a "favorites" playlist, give it a name/description to match
  def name_favorites_and_set_permalink
    self.title = self.description = self.user.name + "'s favorite tracks" if self.is_favorite?
    generate_permalink!
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  before_filter :find_user, :except => :all
  before_filter :find_playlists, :except => [:index, :new, :create, :sort, :all]
  before_filter :require_login, :except => [:index, :show, :all]
  before_filter :find_tracks, :only => [:show, :edit, :all]

  def all
    @playlists = Playlist.recent.only_public.with_pic.
                   paginate(:page => params[:page], :per_page => 20)
  end

  # all user's playlists
  def index
    @page_title = @description  = "#{@user.name}'s albums and playlists: "
    set_all_playlists
  end

  def sort
    respond_to do |format|
      format.html { @playlists = @user.playlists.include_private.all }
      format.js do
        params["playlist"].each_with_index do |id, position|
          @user.playlists.update(id, :position => position+1)
        end
        render :nothing => true
      end
    end
  end

  def favorites
    @playlist = @user.favorites
    redirect_to user_playlist_path(@user, @playlist)
  end

  def show
    @page_title = @description = "\"#{@playlist.title}\" by #{@user.name}"
    @single_playlist = true
  end

  def new
    @playlist = @user.playlists.build(:private => true)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @playlist }
    end
  end

  def edit
    set_assets
    @listens = @user.listened_to_tracks.preload(:user).
                 select('assets.*').distinct.
                 paginate(:page => params[:listens_page], :per_page => 10)
    @favorites = @user.favorites.tracks.paginate(:page => params[:favorites_page], :per_page => 10) if @user.favorites.present?
    if request.xhr?
      render_desired_partial
    end
  end

  def add_track
    id = params[:asset_id].split("_")[1]
    asset = Asset.find(id)
    @track = @playlist.tracks.create(:asset => asset)
    respond_to do |format|
      format.js
    end
  rescue ActiveRecord::RecordNotFound, NoMethodError
    return head(:bad_request)
  end

  def attach_pic
    if params[:pic].present?
      @pic = @playlist.build_pic(params[:pic])
      flash[:notice] = 'Picture updated!' if @pic.save
    end
    flash[:error] = 'Whups, picture not updated! Try again.' unless flash[:notice].present?
    redirect_to edit_user_playlist_path(@user, @playlist)
  end

  def remove_track
    @track = @playlist.tracks.find(params[:track_id])
    if @track && @track.destroy
      respond_to do |format|
        format.js {return head(:ok); render :nothing => true}
      end
    else
      render :nothing => true
    end
  rescue ActiveRecord::RecordNotFound
    head(:bad_request)
  end

  def sort_tracks
    # get the params for this playlist
    params["track"].each_with_index do |id, position|
      Track.update(id, :position => position+1)
    end
    render :nothing => true
  end


  def create
    @playlist = @user.playlists.build(params[:playlist])
    if @playlist.save
      flash[:notice] = 'Great, go ahead and add some tracks'
       redirect_to edit_user_playlist_path(@user, @playlist)
    else
       render :action => "new"
    end
  end

  def update
    if @playlist.update_attributes(params[:playlist])
      redirect_to edit_user_playlist_path(@user,@playlist), :notice => 'Playlist was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @playlist.destroy
    flash[:notice] = "That playlist is toast."
    redirect_to(user_playlists_url(@user))
  end

  protected

  def render_desired_partial
    render :partial => 'your_stuff.html.erb'     if params[:uploads_page]
    render :partial => 'your_listens.html.erb'   if params[:listens_page]
    render :partial => 'your_favorites.html.erb' if params[:favorites_page]
  end

  def set_assets
    @assets = @user.assets.recent.paginate(:page => params[:uploads_page], :per_page => 10)
  end

  def set_all_playlists
    @all_playlists =  current_user_is_admin_or_owner?(@user) ?
                      @user.playlists.include_private :
                      @user.playlists.only_public

    set_right_and_left_playlists if @all_playlists.present?
  end

  def set_right_and_left_playlists
    middle = (@all_playlists.size + 1) / 2
    @playlists_left  = @all_playlists[ 0 ... middle ]
    @playlists_right = @all_playlists[ middle .. -1 ]
  end


  def authorized?
    @playlist.nil? || current_user_is_admin_or_owner?(@playlist.user) ||
    %w[ destroy admin edit update remove_track attach_pic sort_tracks
        add_track set_playlist_description set_playlist_title ].include?(action_name) == false
  end

  def find_playlists
    permalink = params[:permalink] || params[:id]
    @playlist = @user.playlists.where(:permalink => permalink).first || @user.playlists.where(:id => permalink).take!
  end

  def find_tracks
    @tracks = @playlist.tracks if @playlist
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  
  def title_and_year_for(playlist)
    title = "#{playlist.title}"
    title += " (#{playlist.year})" if playlist.year
    title
  end
end

app/views/playlists/_asset.html.erb
<%= content_tag :div, :id => ("asset_#{asset.id}"), :class => 'asset unopenable ' do %>
  <%= render :layout => 'assets/asset_layout', :locals => {:asset => asset} do %>
     <%= link_to asset.user.name, user_home_path(asset.user), :class => 'artist' %>
  <% end %>
<% end %>

app/views/playlists/_form.html.erb
<p>
  <strong>Title</strong><br>
  <%= f.text_field :title %>
</p>

<p>
  <strong>Year released (e.g. 2008)</strong><br>
  <%= f.text_field :year, :size => 4 %>
</p>
<p>
  <strong>Description</strong><br>
  <%= f.text_area :description, :rows => 4 %>
</p>

<p>
  <strong>Hidden from the public?</strong><br>
  <%= f.check_box :private %><br>
  <span style="font-size: 12px">(Playlist will always be hidden until they have more than 2 tracks)</span>
</p>

app/views/playlists/_inline_help.html.erb
<%= notice_for('edit_playlist',"Editing '#{@playlist.title}'") do %>
    <ol>
        <li>Find the track you want to add</li>
        <li>Drag track to your playlist on the left</li>
        <li>Repeat!</li>
        <li>Order tracks in your playlist by dragging them up and down</li>
    </ol>
<% end %>

app/views/playlists/_play_time.html.erb
<span id="play_time"><%= @playlist.play_time %></span>

app/views/playlists/_row.html.erb
<%= cache(cache_digest(playlists)) do %>
  <div class="playlists_row">
    <ul>
      <% playlists.each do |playlist| %>
        <li>
          <%= link_to ' ',user_playlist_path(playlist.user.login, playlist), :title => "#{playlist.title} by #{playlist.user.name}", :class=> "overlay" %>
          <%= image_tag(playlist.cover(:album), :alt => "#{playlist.title} by #{playlist.user.name}") %>
          <div class="playlists_home_title">
            <%= link_to truncate(playlist.title, :length => 26), user_playlist_path(playlist.user.login, playlist), :title => "#{playlist.title} by #{playlist.user.name}" %>
          </div>
          <div class="playlists_home_user">
            <%= link_to truncate(playlist.user.name, :length => 26), user_playlist_path(playlist.user.login, playlist) %>
          </div>
        </li>
      
      <% end %>
    </ul>
  </div>
<% end %>



<%= cache(cache_digest(playlists)) do %>
<% playlists.each do |playlist| %>
<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                      <div class="item">
                        <div class="pos-rlt">
                          <!-- <div class="bottom">
                            <span class="badge bg-info m-l-sm m-b-sm">03:20</span>
                          </div> 
                          <div class="item-overlay opacity r r-2x bg-black">
                            <div class="text-info padder m-t-sm text-sm">
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star-o text-muted"></i>
                            </div>
                            <div class="center text-center m-t-n">
                              <a href="#"><i class="icon-control-play i-2x"></i></a>
                            </div>
                            <div class="bottom padder m-b-sm">
                              <a href="#" class="pull-right">
                                <i class="fa fa-heart-o"></i>
                              </a>
                              <a href="#">
                                <i class="fa fa-plus-circle"></i>
                              </a>
                            </div>
                          </div>-->
                          <%= link_to (image_tag(playlist.cover(:album), :alt => "#{playlist.title} by #{playlist.user.name}"), :class=> "r r-2x img-full"),user_playlist_path(playlist.user.login, playlist), :title => "#{playlist.title} by #{playlist.user.name}", :class=> "overlay" %>
                        </div>
                        <div class="padder-v">
                          <%= link_to truncate(playlist.title, :length => 26), user_playlist_path(playlist.user.login, playlist), :title => "#{playlist.title} by #{playlist.user.name}" %>
                          <%= link_to truncate(playlist.user.name, :length => 26), user_playlist_path(playlist.user.login, playlist) %>
                        </div>
                      </div>
                    </div>
          <% end %>
  <% end %>

app/views/playlists/_share.html.erb
<h2 class="box">Share this playlist</h2>
<div class="box">
    <div class="static_content panel no_border">
        <h3>Link to this playlist</h3>
        <%= text_field_tag "link_#{playlist.id.to_s}","#{user_playlist_url(playlist.user.login, playlist)}", :size => 50%>
    </div>
    <div class="static_content panel">
        <h3>Embed a flash player</h3>
        <%= text_area_tag "flash_player_#{playlist.id.to_s}", "<embed src=\"#{FLASH_PLAYER}\" width=\"320\" height=\"140\" allowfullscreen=\"true\" allowscriptaccess=\"always\" flashvars=\"&file=#{user_playlist_url(playlist.user, playlist, :format => :xml)}&height=140&width=320&frontcolor=0x3C3C3C&backcolor=0xf3f3f3&lightcolor=0xFF944B&screencolor=0xFF944B&displaywidth=120&showdigits=false&showdownload=true\" />", :rows => 3, :cols => 50 %>
        (customize how it looks by visiting <%= link_to 'the setup wizard', 'http://www.jeroenwijering.com/?page=wizard&example=2'%>)
    </div>
</div>

app/views/playlists/_tracks.html.erb
<% div_for @playlist do %>
	<%= render :partial => 'asset', :collection => @tracks %>	
<% end %>

app/views/playlists/_your_favorites.html.erb
<div id="your_favorites" class="playlist_source">
  <div class="mini_paginator">
    <%= will_paginate @favorites, {:param_name => :favorites_page, :ignore_get_params => true}%>
  </div>
	
	<div class="scriptaculous">
	  <%= render :partial => 'playlists/asset', :collection => @favorites.collect(&:asset) %>
	</div>
</div>

app/views/playlists/_your_listens.html.erb
<div id="your_listens" class="playlist_source">
  <div class="mini_paginator">
    <%= will_paginate @listens,{:param_name => :listens_page, :ignore_get_params => true} %>
	</div>
	<div class="scriptaculous">
	<%= render :partial => 'listen', :collection => @listens %>
	</div>
</div>

app/views/playlists/_your_stuff.html.erb
<div id="your_uploads" class="playlist_source">
  <div class="mini_paginator">
    <%= will_paginate @assets, {:param_name => :uploads_page, :ignore_get_params => true}%>
  </div>
	
	<div class="scriptaculous">
	  <%= render :partial => 'playlists/asset', :collection => @assets %>
	</div>
</div>

app/views/playlists/add_track.js.erb
<%= render :partial => 'track.html.erb', :object => @track %>

app/views/playlists/index.html.erb
<%= render(:partial => 'users/user') %>
<% if authorized? %>
<div class="additional_options_solo">
  <div class="button_wrapper">
  <%= link_to image_tag("icons/plus.png") + "create new playlist", new_user_playlist_path(@user), :id => 'create_new_playlist', :class => 'button' %>
  </div>
  <% if @user.playlists.only_public.size > 1 %>
    <div class="button_wrapper">
    <%= link_to image_tag("icons/arrows.png") + "change playlist order", sort_user_playlists_path(@user.login), :id => 'change_playlist_order', :class => 'button'  %>
    </div>
  <% end %>
</div>
<% end %>
<% content_for :main do %>
  <%= render :partial => 'playlist', :collection => @playlists_left if @playlists_left %>

  <%= render :partial => 'playlist', :collection => @playlists_right if @playlists_right %>
<% end %>

app/views/playlists/new.html.erb
<%= render(:partial => 'users/user') %>

<h1>Create a new album or mix</h1>
<h2 class="spacey">Your playlist will become public as soon as it has some tracks in it</h2>

<%= error_messages_for :playlist %>


<div class="container static_content">
<%= form_for [@user, @playlist] do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>
</div>

app/views/playlists/show.html.erb
<%= render :partial => 'users/user' %>

<% content_for :main do %>
  <div id="single_playlist">
    <% cache([@playlist, authorized_for(@playlist)]) do %>
      <%= render @playlist %>
    <% end unless (@playlist.private? && authorized_for(@playlist)) # don't cache private playlists %>
  </div>  	

  <%= render :partial => 'share', :locals => {:playlist => @playlist} %>
<% end %>